### PR TITLE
add support for the Core. Fixes issue #5

### PR DESCRIPTION
**Pull request by m-mcgowan**

### CODE REVIEW

**Comment by suda** [comment]
I've updated this PR to latest master.

@m-mcgowan could you also add test case for this binary? :)

**Comment by dmiddlecamp** [comment]
Heya @suda,

  What's the status of this branch?  I ran into an issue with the standard buildpack because it was expecting changes from this branch.

Thanks,
David

**Comment by suda** [comment]
@dmiddlecamp np! As for PR, it should work but I would love some test cases for Core (wink, wink @m-mcgowan )

**Comment by m-mcgowan** [comment]
There's a binary in this commit - https://github.com/spark/binary-version-reader/commit/8c6af240a29138b1d4b9072b0f97a2a5c1880de4.  If you're asking me to add test cases, I can have a go at that.

**Comment by suda** [comment]
@m-mcgowan that would be lovely :)

**Pull request merged**
